:questions:
  - :kanji: "キーボードをつくらないと"
    :kana: "きーぼーどをつくらないと"
  - :kanji: "キーボードなんもわからん"
    :kana: "きーぼーどなんもわからん"
  - :kanji: "にるぽケ1000本出品する"
    :kana: "にるぽけ1000ほんしゅっぴんする"
  - :kanji: "悪目立ち中二病あいどる"
    :kana: "わるめだちちゅうにびょうあいどる"
  - :kanji: "軍曹には気をつけろ"
    :kana: "ぐんそうにはきをつけろ"
  - :kanji: "黄色いドットアイコンは強さの証"
    :kana: "きいろいどっとあいこんはつよさのあかし"
  - :kanji: "kawazuがこちらを見つめている"
    :kana: "かわずがこちらをみつめている"
  - :kanji: "電脳世界を翔ける銀翼の翼"
    :kana: "でんのうせかいをかけるぎんよくのつばさ"
  - :kanji: "情報化社会を切り裂く剣"
    :kana: "じょうほうかしゃかいをきりさくつるぎ"
  - :kanji: "キーボードなんもわからん"
    :kana: "きーぼーどなんもわからん"
  - :kanji: "エンドゲームは移りゆくもの"
    :kana: "えんどげーむはうつりゆくもの"
  - :kanji: "ドゥルドゥルを追い求めて"
    :kana: "どぅるどぅるをおいもとめて"

